apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- ../../base


#- path: ./patches/deployment-patch.yaml
#  target:
#    kind: Deployment
#    version: v1
   


patches:
- path: ./patches/ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    version: v1
- path: ./patches/rollout-patch.yaml
  target:
    kind: Rollout
    name: gradio-poc
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: gradio-poc
    version: v1

images:
- name: developementRegistry.azurecr.io/gradio-poc
  newTag: 4a6844b4b377eb66274c458f13be431ce847f020
